# # train teacher with or without task dropout
# CUDA_VISIBLE_DEVICES=2,3 python tools/train_net.py --num-gpus 2 --config-file configs/COCO-Detection-liuxu/retinanet_MBV3Large_FPN_1x.yaml
# CUDA_VISIBLE_DEVICES=2,3 python tools/train_net.py --num-gpus 2 --config-file configs/COCO-Detection-liuxu/retinanet_MBV3Large_FPN_1x-task_dropout.yaml
# CUDA_VISIBLE_DEVICES=2,3 python tools/train_net.py --num-gpus 2 --config-file configs/COCO-Detection-liuxu/retinanet_MBV3Large_FPN_1x-Full_BN.yaml
# CUDA_VISIBLE_DEVICES=2,3 python tools/train_net.py --num-gpus 2 --config-file configs/COCO-Detection-liuxu/retinanet_MBV3Large_FPN_1x-Full_BN-task_dropout.yaml
# CUDA_VISIBLE_DEVICES=2,3 python tools/train_net.py --num-gpus 2 --config-file configs/COCO-Detection-liuxu/retinanet_MBV3Large_FPN_1x-Full_SyncBN.yaml
# CUDA_VISIBLE_DEVICES=2,3 python tools/train_net.py --num-gpus 2 --config-file configs/COCO-Detection-liuxu/retinanet_MBV3Large_FPN_1x-Full_SyncBN-task_dropout.yaml

# # train ofa with different task dropout ratio, 下面两个添加了 kd loss / normalizer for cls only
# CUDA_VISIBLE_DEVICES=6,7 python tools/train_net.py --dist-url "tcp://127.0.0.1:62645" --num-gpus 2 --resume --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml
# CUDA_VISIBLE_DEVICES=6,7 python tools/train_net.py --dist-url "tcp://127.0.0.1:62645" --num-gpus 2 --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.TASK_DROPOUT_RATE 0.1 OUTPUT_DIR output/coco-detection/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.1

# # 下面两个用了kd loss / normalizer for cls and reg
# CUDA_VISIBLE_DEVICES=0,3 python tools/train_net.py --num-gpus 2 --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.TASK_DROPOUT_RATE 0 OUTPUT_DIR output/coco-detection/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-kd_loss_for_cls+reg
# CUDA_VISIBLE_DEVICES=0,3 python tools/train_net.py --num-gpus 2 --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.TASK_DROPOUT_RATE 0.1 OUTPUT_DIR output/coco-detection/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.1-kd_loss_for_cls+reg

# --dist-url "tcp://127.0.0.1:62645"

# CUDA_VISIBLE_DEVICES=0,1,2,3 python tools/train_net.py --machine-rank 0 --num-machines 2 --dist-url "tcp://gpu015.scut-smil.cn:62645" --num-gpus 4 --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.TASK_DROPOUT_RATE 0 MODEL.OFA_MOBILENETV3.KD_RATIO [1.0,1.0] SOLVER.IMS_PER_BATCH 16 OUTPUT_DIR output/coco-detection/ofa-correct/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-2kd



# # inference
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.0 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-no-kd-this-exp-should-be-correct/model_0009999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.0 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-no-kd-this-exp-should-be-correct/model_0019999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.0 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-no-kd-this-exp-should-be-correct/model_0029999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.0 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-no-kd-this-exp-should-be-correct/model_0039999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.0 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-no-kd-this-exp-should-be-correct/model_0049999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.0 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-no-kd-this-exp-should-be-correct/model_0059999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.0 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-no-kd-this-exp-should-be-correct/model_0069999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.0 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-no-kd-this-exp-should-be-correct/model_0079999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.0 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-no-kd-this-exp-should-be-correct/model_0089999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.0 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-no-kd-this-exp-should-be-correct/model_final.pth

# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [1.0,1.0] MODEL.TASK_DROPOUT_RATE 0.0 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-2kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-2kd_run2/model_0009999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [1.0,1.0] MODEL.TASK_DROPOUT_RATE 0.0 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-2kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-2kd_run2/model_0019999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [1.0,1.0] MODEL.TASK_DROPOUT_RATE 0.0 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-2kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-2kd_run2/model_0029999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [1.0,1.0] MODEL.TASK_DROPOUT_RATE 0.0 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-2kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-2kd_run2/model_0039999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [1.0,1.0] MODEL.TASK_DROPOUT_RATE 0.0 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-2kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-2kd_run2/model_0049999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [1.0,1.0] MODEL.TASK_DROPOUT_RATE 0.0 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-2kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-2kd_run2/model_0059999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [1.0,1.0] MODEL.TASK_DROPOUT_RATE 0.0 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-2kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-2kd_run2/model_0069999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [1.0,1.0] MODEL.TASK_DROPOUT_RATE 0.0 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-2kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-2kd_run2/model_0079999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [1.0,1.0] MODEL.TASK_DROPOUT_RATE 0.0 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-2kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-2kd_run2/model_0089999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [1.0,1.0] MODEL.TASK_DROPOUT_RATE 0.0 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-2kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-2kd_run2/model_final.pth

# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.1 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.1-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.1-no_kd/model_0009999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.1 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.1-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.1-no_kd/model_0019999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.1 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.1-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.1-no_kd/model_0029999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.1 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.1-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.1-no_kd/model_0039999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.1 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.1-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.1-no_kd/model_0049999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.1 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.1-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.1-no_kd/model_0059999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.1 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.1-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.1-no_kd/model_0069999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.1 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.1-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.1-no_kd/model_0079999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.1 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.1-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.1-no_kd/model_0089999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.1 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-old-losswrong-test/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.1-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.1-no_kd/model_final.pth







# inference
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [1.0,1.0] MODEL.TASK_DROPOUT_RATE 0.05 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/task_dropout_ratio_ablation/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa-correct-really/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd/model_0069999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [1.0,1.0] MODEL.TASK_DROPOUT_RATE 0.05 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/task_dropout_ratio_ablation/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa-correct-really/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd/model_0079999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [1.0,1.0] MODEL.TASK_DROPOUT_RATE 0.05 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/task_dropout_ratio_ablation/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa-correct-really/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd/model_0089999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [1.0,1.0] MODEL.TASK_DROPOUT_RATE 0.05 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/task_dropout_ratio_ablation/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa-correct-really/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd/model_final.pth

CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.05 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/task_dropout_ratio_ablation/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa-correct-really/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-no-kd/model_0029999.pth
CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.05 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/task_dropout_ratio_ablation/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa-correct-really/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-no-kd/model_0039999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.05 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/task_dropout_ratio_ablation/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa-correct-really/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-no-kd/model_0049999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.05 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/task_dropout_ratio_ablation/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa-correct-really/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-no-kd/model_0059999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.05 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/task_dropout_ratio_ablation/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa-correct-really/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-no-kd/model_0069999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.05 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/task_dropout_ratio_ablation/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa-correct-really/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-no-kd/model_0079999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.05 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/task_dropout_ratio_ablation/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa-correct-really/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-no-kd/model_0089999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [0.0,0.0] MODEL.TASK_DROPOUT_RATE 0.05 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/task_dropout_ratio_ablation/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-no-kd MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa-correct-really/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-no-kd/model_final.pth


# # 测试一下不同的bn set size，对于测试性能的影响
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [1.0,1.0] MODEL.TASK_DROPOUT_RATE 0.05 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/BN_SET_SIZE_ablation/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd-BN MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa-correct-really/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd/model_0069999.pth DATALOADER.BN_SUBSET_SIZE 200
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [1.0,1.0] MODEL.TASK_DROPOUT_RATE 0.05 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/BN_SET_SIZE_ablation/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd-BN MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa-correct-really/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd/model_0069999.pth DATALOADER.BN_SUBSET_SIZE 400
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [1.0,1.0] MODEL.TASK_DROPOUT_RATE 0.05 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/BN_SET_SIZE_ablation/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd-BN MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa-correct-really/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd/model_0069999.pth DATALOADER.BN_SUBSET_SIZE 600
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [1.0,1.0] MODEL.TASK_DROPOUT_RATE 0.05 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/BN_SET_SIZE_ablation/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd-BN MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa-correct-really/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd/model_0069999.pth DATALOADER.BN_SUBSET_SIZE 800
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [1.0,1.0] MODEL.TASK_DROPOUT_RATE 0.05 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/BN_SET_SIZE_ablation/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd-BN MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa-correct-really/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd/model_0069999.pth DATALOADER.BN_SUBSET_SIZE 1000
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [1.0,1.0] MODEL.TASK_DROPOUT_RATE 0.05 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/BN_SET_SIZE_ablation/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd-BN MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa-correct-really/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd/model_0069999.pth DATALOADER.BN_SUBSET_SIZE 1200
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [1.0,1.0] MODEL.TASK_DROPOUT_RATE 0.05 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/BN_SET_SIZE_ablation/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd-BN MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa-correct-really/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd/model_0069999.pth DATALOADER.BN_SUBSET_SIZE 1400
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [1.0,1.0] MODEL.TASK_DROPOUT_RATE 0.05 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/BN_SET_SIZE_ablation/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd-BN MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa-correct-really/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd/model_0069999.pth DATALOADER.BN_SUBSET_SIZE 1600
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [1.0,1.0] MODEL.TASK_DROPOUT_RATE 0.05 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/BN_SET_SIZE_ablation/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd-BN MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa-correct-really/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd/model_0069999.pth DATALOADER.BN_SUBSET_SIZE 1800
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout=0.yaml MODEL.OFA_MOBILENETV3.KD_RATIO [1.0,1.0] MODEL.TASK_DROPOUT_RATE 0.05 SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/BN_SET_SIZE_ablation/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd-BN MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa-correct-really/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.05-2kd/model_0069999.pth DATALOADER.BN_SUBSET_SIZE 2000


# 测一下之前train的teacher，它也是被拿来作为ofa的teacher的ckpt，而不是新训练的，最好两次训练的ckpt性能差不多，不然ofa又要改为新train的really correct的teacher重新跑

# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_MBV3Large_FPN_1x-task_dropout=0.yaml SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/teacher_retinanet_MBV3Large_FPN_1x_task_dropout=0_oldone MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/retinanet_MBV3Large_FPN_1x_task_dropout=0_run2-with-SyncBN/model_0009999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_MBV3Large_FPN_1x-task_dropout=0.yaml SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/teacher_retinanet_MBV3Large_FPN_1x_task_dropout=0_oldone MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/retinanet_MBV3Large_FPN_1x_task_dropout=0_run2-with-SyncBN/model_0019999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_MBV3Large_FPN_1x-task_dropout=0.yaml SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/teacher_retinanet_MBV3Large_FPN_1x_task_dropout=0_oldone MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/retinanet_MBV3Large_FPN_1x_task_dropout=0_run2-with-SyncBN/model_0029999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_MBV3Large_FPN_1x-task_dropout=0.yaml SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/teacher_retinanet_MBV3Large_FPN_1x_task_dropout=0_oldone MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/retinanet_MBV3Large_FPN_1x_task_dropout=0_run2-with-SyncBN/model_0039999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_MBV3Large_FPN_1x-task_dropout=0.yaml SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/teacher_retinanet_MBV3Large_FPN_1x_task_dropout=0_oldone MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/retinanet_MBV3Large_FPN_1x_task_dropout=0_run2-with-SyncBN/model_0049999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_MBV3Large_FPN_1x-task_dropout=0.yaml SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/teacher_retinanet_MBV3Large_FPN_1x_task_dropout=0_oldone MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/retinanet_MBV3Large_FPN_1x_task_dropout=0_run2-with-SyncBN/model_0059999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_MBV3Large_FPN_1x-task_dropout=0.yaml SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/teacher_retinanet_MBV3Large_FPN_1x_task_dropout=0_oldone MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/retinanet_MBV3Large_FPN_1x_task_dropout=0_run2-with-SyncBN/model_0069999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_MBV3Large_FPN_1x-task_dropout=0.yaml SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/teacher_retinanet_MBV3Large_FPN_1x_task_dropout=0_oldone MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/retinanet_MBV3Large_FPN_1x_task_dropout=0_run2-with-SyncBN/model_0079999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_MBV3Large_FPN_1x-task_dropout=0.yaml SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/teacher_retinanet_MBV3Large_FPN_1x_task_dropout=0_oldone MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/retinanet_MBV3Large_FPN_1x_task_dropout=0_run2-with-SyncBN/model_0089999.pth
# CUDA_VISIBLE_DEVICES=6 python tools/train_net.py --num-gpus 1 --eval-only --config-file configs/COCO-Detection-liuxu/retinanet_MBV3Large_FPN_1x-task_dropout=0.yaml SOLVER.IMS_PER_BATCH 8 OUTPUT_DIR output/coco-detection/ofa-correct-really-test/teacher_retinanet_MBV3Large_FPN_1x_task_dropout=0_oldone MODEL.WEIGHTS /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/retinanet_MBV3Large_FPN_1x_task_dropout=0_run2-with-SyncBN/model_final.pth



# build acc dataset
# generate net_id_part
python tools/train_net.py --num-gpus 1 --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout-build_acc_dataset.yaml MODEL.BUILD_ACC_DATASET.JUST_BUILD_NET_ID True
source /mnt/cephfs/home/liuxu/miniconda3/bin/activate && conda activate d2 && cd /mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/ && export PYTHONPATH=$PYTHONPATH:mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/
# each part build acc dataset
CUDA_VISIBLE_DEVICES=0 python tools/train_net.py --num-gpus 1 --config-file configs/COCO-Detection-liuxu/retinanet_ofa_MBV3Large_FPN_1x-task_dropout-build_acc_dataset.yaml OUTPUT_DIR output/coco-detection/build_acc_dataset/just_net_id_generation MODEL.BUILD_ACC_DATASET.NET_ID_PART_INDEX 1
