_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  OFA_SEARCH:
    ENABLED: True
    ALL_TASK: False
    SEED: 2021
    ONLY_SHOW_TIME: False
    PREDICTOR_CKPT: "/mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/predictor/debug/best.pth"
    OFA_CKPT: "/mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa-correct-really/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0-2kd/model_final.pth"
    CONSTRAINT_LOW: 180
    CONSTRAINT_HIGH: 400
    CONSTRAINT_INTERVAL: 50
    REPORT_FREQ: 10
    NUM_SAMPLE: 10
  IS_OFA: True
  BACKBONE:
    NAME: "build_retinanet_ofa_mbv3_fpn_backbone"
    FREEZE_AT: 10 # correspond to freeze at 2 in resnet
  FPN:
    IN_FEATURES: ["res2", "res4", "res5"]
    USE_RELU: True
DATASETS:
  TRAIN: ("coco_2017_train_task_dropout",)
  TEST: ("coco_2017_val_task_dropout",)
OUTPUT_DIR: output/coco-detection/ofa-search/debug