_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "/mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/weights/det-resnet18/official-r18.pth.raw"
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
  BACKBONE:
    FREEZE_AT: 0
DATASETS:
  TRAIN: ("coco_2017_train_50",)
  TEST: ("coco_2017_val_50",)
OUTPUT_DIR: output/coco-detection/retinanet_R_18_FPN_1x-debug