_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  GENERATOR_ARCH:
    ENABLED: True
    TYPE: "SP" # SP or MP, but MP is not supported
    TEST_INTERVAL: 50
    CONTROLLER_CKPT: "/mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/controller/retinanet_controller_MBV3Large_FPN_1x_SP_run2/model_0029999.pth"
  BACKBONE:
    NAME: "build_retinanet_ofa_mbv3_fpn_backbone"
    FREEZE_AT: 10 # correspond to freeze at 2 in resnet
  FPN:
    IN_FEATURES: ["res2", "res4", "res5"]
    USE_RELU: True
DATASETS:
  TRAIN: ("coco_2017_train_task_dropout_50",)
  TEST: ("coco_2017_val_task_dropout_50",)
OUTPUT_DIR: output/coco-detection/generate_architecture/debug