_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  CONTROLLER:
    NAME: "SP_MobileNetV3Controller"
    TEACHER:
      WEIGHT: "/mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/ofa-correct-really/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.1-2kd/model_final.pth"
  GENERATOR_ARCH:
    ENABLED: True
    TYPE: "SP" # SP or MP, but MP is not supported
    TEST_INTERVAL: 50
    CONTROLLER_CKPT: "/mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/controller/full-data-debug/model_final.pth"
  BACKBONE:
    NAME: "build_retinanet_ofa_mbv3_fpn_backbone"
    FREEZE_AT: 10 # correspond to freeze at 2 in resnet
  FPN:
    IN_FEATURES: ["res2", "res4", "res5"]
    USE_RELU: True
SOLVER:
  IMS_PER_BATCH: 16
DATASETS:
  TRAIN: ("coco_2017_train_task_dropout",)
  TEST: ("coco_2017_val_task_dropout",)
OUTPUT_DIR: output/coco-detection/generate_architecture/0.1-2kd-SP-debug