_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  IS_OFA: True
  OFA_MOBILENETV3:
    DYNAMIC_BATCH_SIZE: 1
    train: True
    teacher: "/mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/retinanet_MBV3Large_FPN_1x_task_dropout=0_run2-with-SyncBN/model_final.pth"
  TASK_DROPOUT_RATE: 0.6
  WEIGHTS: "/mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/detectron2/output/coco-detection/retinanet_MBV3Large_FPN_1x_task_dropout=0_run2-with-SyncBN/model_final.pth"
  BACKBONE:
    NAME: "build_retinanet_ofa_mbv3_fpn_backbone"
    FREEZE_AT: 10 # correspond to freeze at 2 in resnet
  TEACHER_BACKBONE:
    NAME: "build_retinanet_mbv3_fpn_backbone"
  FPN:
    IN_FEATURES: ["res2", "res4", "res5"]
    USE_RELU: True
DATASETS:
  TRAIN: ("coco_2017_train_task_dropout_50",)
  TEST: ("coco_2017_val_task_dropout_50",)
OUTPUT_DIR: output/coco-detection/ofa/retinanet_ofa_MBV3Large_FPN_1x_task_dropout=0.6_debug