_BASE_: "Base-Panoptic-FPN.yaml"
MODEL:
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  WEIGHTS: "/mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/weights/PanopticSeg/model_final_cafdb1.pkl"
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
OUTPUT_DIR: output/coco-segmentation/panoptic_fpn_R_101_3x